import { useCallback, useEffect, useRef } from "react";
import type { Dispatch, MutableRefObject } from "react";
import * as Sentry from "@sentry/react";
import { useI18nSafe } from "../../../hooks/useI18nSafe";
import type {
  AppMention,
  ComposerSendIntent,
  RateLimitSnapshot,
  CustomPromptOption,
  DebugEntry,
  ReviewTarget,
  SendMessageResult,
  ServiceTier,
  WorkspaceInfo,
} from "@/types";
import {
  compactThread as compactThreadService,
  sendUserMessage as sendUserMessageService,
  steerTurn as steerTurnService,
  startReview as startReviewService,
  interruptTurn as interruptTurnService,
  getAppsList as getAppsListService,
  listMcpServerStatus as listMcpServerStatusService,
  sendClaudeCodePrompt,
  stopClaudeCodePrompt,
} from "@services/tauri";
import { subscribeClaudeCodeEvents } from "@services/events";
import {
  asRecord,
  buildClaudeCodeToolItem,
  buildClaudeCodeTextUserInputItem,
  buildClaudeCodeUserInputItem,
  claudeCodeToolOutput,
  isClaudeCodeUserQuestionTool,
  parseJsonObject,
  stringValue,
  toolResultText,
  type JsonRecord,
} from "@/features/messages/utils/claudeCodeTools";
import { generateThreadTitle } from "@services/threadTitle";
import { expandCustomPromptText } from "@utils/customPrompts";
import { clampThreadName, looksAutoGeneratedThreadName } from "@threads/utils/threadNaming";
import {
  asString,
  extractReviewThreadId,
  extractRpcErrorMessage,
  parseReviewTarget,
} from "@threads/utils/threadNormalize";
import type { ThreadAction, ThreadState } from "./useThreadsReducer";
import { useReviewPrompt } from "./useReviewPrompt";
import {
  appendAttachmentPathsToText,
  buildAppsLines,
  buildMcpStatusLines,
  buildReviewThreadTitle,
  buildStatusLines,
  buildTurnStartPayload,
  extractImageAttachments,
  isStaleSteerTurnError,
  parseFastCommand,
  resolveSendMessageOptions,
  type SendMessageOptions,
} from "./threadMessagingHelpers";

type UseThreadMessagingOptions = {
  activeWorkspace: WorkspaceInfo | null;
  activeThreadId: string | null;
  accessMode?: "read-only" | "current" | "full-access";
  model?: string | null;
  effort?: string | null;
  serviceTier?: ServiceTier | null | undefined;
  collaborationMode?: Record<string, unknown> | null;
  onSelectServiceTier?: (tier: ServiceTier | null | undefined) => void;
  reviewDeliveryMode?: "inline" | "detached";
  steerEnabled: boolean;
  customPrompts: CustomPromptOption[];
  ensureWorkspaceRuntimeCodexArgs?: (
    workspaceId: string,
    threadId: string | null,
  ) => Promise<void>;
  shouldPreflightRuntimeCodexArgsForSend?: (
    workspaceId: string,
    threadId: string,
  ) => boolean;
  threadStatusById: ThreadState["threadStatusById"];
  activeTurnIdByThread: ThreadState["activeTurnIdByThread"];
  itemsByThread: ThreadState["itemsByThread"];
  threadsByWorkspace: ThreadState["threadsByWorkspace"];
  rateLimitsByWorkspace: Record<string, RateLimitSnapshot | null>;
  pendingInterruptsRef: MutableRefObject<Set<string>>;
  dispatch: Dispatch<ThreadAction>;
  getCustomName: (workspaceId: string, threadId: string) => string | undefined;
  markProcessing: (threadId: string, isProcessing: boolean) => void;
  markReviewing: (threadId: string, isReviewing: boolean) => void;
  setActiveTurnId: (threadId: string, turnId: string | null) => void;
  setInterruptedTurnId: (threadId: string, turnId: string | null) => void;
  recordThreadActivity: (
    workspaceId: string,
    threadId: string,
    timestamp?: number,
  ) => void;
  safeMessageActivity: () => void;
  onDebug?: (entry: DebugEntry) => void;
  pushThreadErrorMessage: (threadId: string, message: string) => void;
  ensureThreadForActiveWorkspace: () => Promise<string | null>;
  ensureThreadForWorkspace: (workspaceId: string) => Promise<string | null>;
  refreshThread: (workspaceId: string, threadId: string) => Promise<string | null>;
  forkThreadForWorkspace: (
    workspaceId: string,
    threadId: string,
    options?: { activate?: boolean },
  ) => Promise<string | null>;
  updateThreadParent: (parentId: string, childIds: string[]) => void;
  registerDetachedReviewChild?: (
    workspaceId: string,
    parentId: string,
    childId: string,
  ) => void;
  renameThread?: (workspaceId: string, threadId: string, name: string) => void;
};

function buildImmediateThreadTitle(prompt: string) {
  const cleaned = prompt
    .replace(/\[image(?: x\d+)?\]/gi, " ")
    .replace(/@'((?:\\.|[^'\\\n])*)'/g, " ")
    .replace(/\[[^\]\n]+\]\([^)]+\)/g, " ")
    .replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ")
    .replace(/[`*_~>#-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return clampThreadName(cleaned, 24);
}

export function useThreadMessaging({
  activeWorkspace,
  activeThreadId,
  accessMode,
  model,
  effort,
  serviceTier,
  collaborationMode,
  onSelectServiceTier,
  reviewDeliveryMode = "inline",
  steerEnabled,
  customPrompts,
  ensureWorkspaceRuntimeCodexArgs,
  shouldPreflightRuntimeCodexArgsForSend,
  threadStatusById,
  activeTurnIdByThread,
  itemsByThread,
  threadsByWorkspace,
  rateLimitsByWorkspace,
  pendingInterruptsRef,
  dispatch,
  getCustomName,
  markProcessing,
  markReviewing,
  setActiveTurnId,
  setInterruptedTurnId,
  recordThreadActivity,
  safeMessageActivity,
  onDebug,
  pushThreadErrorMessage,
  ensureThreadForActiveWorkspace,
  ensureThreadForWorkspace,
  refreshThread,
  forkThreadForWorkspace,
  updateThreadParent,
  registerDetachedReviewChild,
  renameThread,
}: UseThreadMessagingOptions) {
  const { t } = useI18nSafe();
  const requestedInitialThreadTitlesRef = useRef<Set<string>>(new Set());
  const claudeStreamItemIdByChatRef = useRef<Record<string, string>>({});
  const claudeSessionIdByChatRef = useRef<Record<string, string>>({});
  // Per-chat streaming state for Claude Code tool calls. The raw stream event
  // carries tool_use/tool_result blocks (Read/Write/Edit/Bash/...) that the
  // text/thinking extractors skip; we parse them here so tools render mid-turn.
  const claudeStreamStateByChatRef = useRef<
    Record<
      string,
      {
        tools: Map<string, { name: string; inputBuffer: string; input: JsonRecord | null; itemId: string }>;
        indexToToolUseId: Map<number, string>;
        userInputIds: Map<string, string>;
        textByItemId: Map<string, string>;
        segment: number;
        hadDelta: boolean;
      }
    >
  >({});

  useEffect(() => subscribeClaudeCodeEvents((streamEvent) => {
    const chatId = streamEvent.chatId;
    const workspaceId = streamEvent.workspaceId;
    const baseItemId = claudeStreamItemIdByChatRef.current[chatId];
    if (!baseItemId) {
      return;
    }
    let streamState = claudeStreamStateByChatRef.current[chatId];
    if (!streamState) {
      streamState = {
        tools: new Map(),
        indexToToolUseId: new Map(),
        userInputIds: new Map(),
        textByItemId: new Map(),
        segment: 0,
        hadDelta: false,
      };
      claudeStreamStateByChatRef.current[chatId] = streamState;
    }

    // Thinking deltas are intentionally not rendered (the user opted out of
    // showing Claude's reasoning), so we drop streamEvent.deltaThinking here.

    // ---- tool calls (Read/Write/Edit/Bash/...) from the raw stream event ----
    const rawEventRecord = asRecord(streamEvent.event);
    const innerEvent =
      rawEventRecord && rawEventRecord.type === "stream_event"
        ? asRecord(rawEventRecord.event)
        : rawEventRecord;
    const eventType = innerEvent?.type;
    const blockIndex = typeof innerEvent?.index === "number" ? innerEvent.index : -1;

    if (eventType === "content_block_start") {
      const contentBlock = asRecord(innerEvent?.content_block);
      if (contentBlock?.type === "tool_use") {
        const toolUseId = stringValue(contentBlock.id);
        const toolName = stringValue(contentBlock.name) || "Tool";
        if (toolUseId) {
          // Rotate the active text bubble so assistant text emitted after this
          // tool lands in a fresh bubble below it — matches history + Codex
          // interleaving. findCurrentTurnAssistantIndex matches `${base}#turn-N`.
          streamState.segment += 1;
          claudeStreamItemIdByChatRef.current[chatId] = `${baseItemId}#turn-${streamState.segment}`;
          const toolItemId = `${baseItemId}::tool::${toolUseId}`;
          const initialInput = asRecord(contentBlock.input) ?? {};
          streamState.tools.set(toolUseId, {
            name: toolName,
            inputBuffer: "",
            input: Object.keys(initialInput).length ? initialInput : null,
            itemId: toolItemId,
          });
          if (blockIndex >= 0) {
            streamState.indexToToolUseId.set(blockIndex, toolUseId);
          }
          if (isClaudeCodeUserQuestionTool(toolName)) {
            const userInputId = `${baseItemId}::user-input::${toolUseId}`;
            streamState.userInputIds.set(toolUseId, userInputId);
            dispatch({
              type: "upsertItem",
              workspaceId,
              threadId: chatId,
              item: buildClaudeCodeUserInputItem({
                id: userInputId,
                input: initialInput,
              }),
            });
            safeMessageActivity();
            return;
          }
          dispatch({
            type: "upsertItem",
            workspaceId,
            threadId: chatId,
            item: buildClaudeCodeToolItem({
              id: toolItemId,
              name: toolName,
              input: initialInput,
              status: "inProgress",
            }),
          });
          safeMessageActivity();
        }
      }
    } else if (eventType === "content_block_delta") {
      const delta = asRecord(innerEvent?.delta);
      if (delta?.type === "input_json_delta") {
        const partial = stringValue(delta.partial_json);
        const toolUseId = blockIndex >= 0 ? streamState.indexToToolUseId.get(blockIndex) : undefined;
        const entry = toolUseId ? streamState.tools.get(toolUseId) : undefined;
        if (partial && entry) {
          entry.inputBuffer += partial;
          // Refine the tool's detail as soon as the accumulated input parses.
          // Skip building the diff here — the content is still partial; the
          // full diff is attached at content_block_stop.
          const parsed = parseJsonObject(entry.inputBuffer);
          if (parsed) {
            entry.input = parsed;
            const userInputId = streamState.userInputIds.get(toolUseId ?? "");
            if (userInputId) {
              dispatch({
                type: "upsertItem",
                workspaceId,
                threadId: chatId,
                item: buildClaudeCodeUserInputItem({
                  id: userInputId,
                  input: parsed,
                }),
              });
              return;
            }
            dispatch({
              type: "upsertItem",
              workspaceId,
              threadId: chatId,
              item: buildClaudeCodeToolItem({
                id: entry.itemId,
                name: entry.name,
                input: parsed,
                status: "inProgress",
                includeChanges: false,
              }),
            });
          }
        }
      }
    } else if (eventType === "content_block_stop") {
      const toolUseId = blockIndex >= 0 ? streamState.indexToToolUseId.get(blockIndex) : undefined;
      if (blockIndex >= 0) {
        streamState.indexToToolUseId.delete(blockIndex);
      }
      // Input JSON is complete now: finalize it and (for Write/Edit/MultiEdit)
      // attach the inline diff. The delta-refine path above skipped the diff.
      const entry = toolUseId ? streamState.tools.get(toolUseId) : undefined;
      if (entry) {
        const parsed = entry.inputBuffer ? parseJsonObject(entry.inputBuffer) : null;
        if (parsed) {
          entry.input = parsed;
        }
        const userInputId = streamState.userInputIds.get(toolUseId ?? "");
        if (userInputId) {
          dispatch({
            type: "upsertItem",
            workspaceId,
            threadId: chatId,
            item: buildClaudeCodeUserInputItem({
              id: userInputId,
              input: entry.input ?? {},
            }),
          });
          return;
        }
        dispatch({
          type: "upsertItem",
          workspaceId,
          threadId: chatId,
          item: buildClaudeCodeToolItem({
            id: entry.itemId,
            name: entry.name,
            input: entry.input ?? {},
            status: "inProgress",
          }),
        });
      }
    } else if (eventType === "user" || eventType === "assistant") {
      // Assembled message boundary: carries tool_result (user) and, for
      // assistant messages, the complete tool_use input as a fallback.
      const message = asRecord(innerEvent?.message);
      const contentArr = Array.isArray(message?.content) ? message.content : [];
      for (const unknownBlock of contentArr) {
        const block = asRecord(unknownBlock);
        if (!block) continue;
        const blockType = stringValue(block.type);
        if (blockType === "tool_result") {
          const toolUseId = stringValue(block.tool_use_id);
          const entry = toolUseId ? streamState.tools.get(toolUseId) : undefined;
          if (entry) {
            const resultText = toolResultText(block);
            const userInputId = streamState.userInputIds.get(toolUseId);
            if (userInputId) {
              dispatch({
                type: "upsertItem",
                workspaceId,
                threadId: chatId,
                item: buildClaudeCodeUserInputItem({
                  id: userInputId,
                  input: entry.input ?? {},
                  resultText,
                }),
              });
              safeMessageActivity();
              continue;
            }
            const output = claudeCodeToolOutput(entry.name, entry.input ?? {}, resultText);
            dispatch({
              type: "upsertItem",
              workspaceId,
              threadId: chatId,
              item: buildClaudeCodeToolItem({
                id: entry.itemId,
                name: entry.name,
                input: entry.input ?? {},
                status: block.is_error === true ? "failed" : "completed",
                output,
              }),
            });
            safeMessageActivity();
          }
        } else if (blockType === "tool_use") {
          const toolUseId = stringValue(block.id);
          const entry = toolUseId ? streamState.tools.get(toolUseId) : undefined;
          const completeInput = asRecord(block.input) ?? {};
          if (entry && !entry.input && Object.keys(completeInput).length) {
            entry.input = completeInput;
            dispatch({
              type: "upsertItem",
              workspaceId,
              threadId: chatId,
              item: buildClaudeCodeToolItem({
                id: entry.itemId,
                name: entry.name,
                input: completeInput,
                status: "inProgress",
              }),
            });
          }
        }
      }
    }

    if (streamEvent.deltaText) {
      streamState.hadDelta = true;
      // Read fresh: tool_use events rotate this id so post-tool text starts a
      // new bubble below the tool instead of merging into the one above it.
      const activeTextId = claudeStreamItemIdByChatRef.current[chatId] || baseItemId;
      streamState.textByItemId.set(
        activeTextId,
        `${streamState.textByItemId.get(activeTextId) ?? ""}${streamEvent.deltaText}`,
      );
      dispatch({
        type: "appendAgentDelta",
        workspaceId,
        threadId: chatId,
        itemId: activeTextId,
        delta: streamEvent.deltaText,
        hasCustomName: Boolean(getCustomName(workspaceId, chatId)),
        provider: "claude_code",
      });
      safeMessageActivity();
    }
  }), [dispatch, getCustomName, safeMessageActivity]);
  const maybeGenerateInitialThreadTitle = useCallback(
    async (workspaceId: string, threadId: string, prompt: string) => {
      const requestKey = `${workspaceId}:${threadId}`;
      if (requestedInitialThreadTitlesRef.current.has(requestKey)) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        requestedInitialThreadTitlesRef.current.add(requestKey);
        return;
      }
      const userMessageCount = (itemsByThread[threadId] ?? []).filter(
        (item) => item.kind === "message" && item.role === "user",
      ).length;
      if (userMessageCount > 0) {
        requestedInitialThreadTitlesRef.current.add(requestKey);
        return;
      }
      const currentThread = (threadsByWorkspace[workspaceId] ?? []).find(
        (entry) => entry.id === threadId,
      );
      if (currentThread && !looksAutoGeneratedThreadName(currentThread.name)) {
        requestedInitialThreadTitlesRef.current.add(requestKey);
        return;
      }
      const cleanedPrompt = prompt
        .replace(/\[image(?: x\d+)?\]/gi, " ")
        .replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ")
        .replace(/\s+/g, " ")
        .trim()
        .slice(0, 1200);
      if (!cleanedPrompt) {
        return;
      }
      requestedInitialThreadTitlesRef.current.add(requestKey);
      try {
        const metadata = await generateThreadTitle(cleanedPrompt, workspaceId);
        const title = clampThreadName(metadata.title ?? "");
        if (!title || getCustomName(workspaceId, threadId)) {
          return;
        }
        renameThread?.(workspaceId, threadId, title);
      } catch (error) {
        requestedInitialThreadTitlesRef.current.delete(requestKey);
        onDebug?.({
          id: `${Date.now()}-thread-title-autogen-error`,
          timestamp: Date.now(),
          source: "error",
          label: "thread/title autogen error",
          payload: error instanceof Error ? error.message : String(error),
        });
      }
    },
    [getCustomName, itemsByThread, onDebug, renameThread, threadsByWorkspace],
  );
  const maybeSetImmediateThreadTitle = useCallback(
    (workspaceId: string, threadId: string, prompt: string) => {
      const requestKey = `${workspaceId}:${threadId}`;
      if (requestedInitialThreadTitlesRef.current.has(requestKey)) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        requestedInitialThreadTitlesRef.current.add(requestKey);
        return;
      }
      const userMessageCount = (itemsByThread[threadId] ?? []).filter(
        (item) => item.kind === "message" && item.role === "user",
      ).length;
      if (userMessageCount > 0) {
        requestedInitialThreadTitlesRef.current.add(requestKey);
        return;
      }
      const currentThread = (threadsByWorkspace[workspaceId] ?? []).find(
        (entry) => entry.id === threadId,
      );
      if (currentThread && !looksAutoGeneratedThreadName(currentThread.name)) {
        requestedInitialThreadTitlesRef.current.add(requestKey);
        return;
      }
      const title = buildImmediateThreadTitle(prompt);
      if (!title) {
        return;
      }
      requestedInitialThreadTitlesRef.current.add(requestKey);
      renameThread?.(workspaceId, threadId, title);
    },
    [getCustomName, itemsByThread, renameThread, threadsByWorkspace],
  );

  const sendMessageToThread = useCallback(
    async (
      workspace: WorkspaceInfo,
      threadId: string,
      text: string,
      images: string[] = [],
      options?: SendMessageOptions,
    ): Promise<SendMessageResult> => {
      const messageText = text.trim();
      if (!messageText && images.length === 0) {
        return { status: "blocked" };
      }
      // 新的发送意味着用户已放弃之前的中断意图：清掉残留的 pending interrupt，
      // 避免它错误抑制本轮的流式事件，或在 turn/started 时误触发中断。
      pendingInterruptsRef.current.delete(threadId);
      const rpcImages = extractImageAttachments(images);
      let finalText = messageText;
      if (!options?.skipPromptExpansion) {
        const promptExpansion = expandCustomPromptText(messageText, customPrompts);
        if (promptExpansion && "error" in promptExpansion) {
          pushThreadErrorMessage(threadId, promptExpansion.error);
          safeMessageActivity();
          return { status: "blocked" };
        }
        finalText = promptExpansion?.expanded ?? messageText;
      }
      finalText = appendAttachmentPathsToText(finalText, images);
      if (workspace.source === "claude_code") {
        const timestamp = Date.now();
        const streamItemId = `${threadId}-claude-${timestamp}`;
        const storedThread = (threadsByWorkspace[workspace.id] ?? []).find(
          (thread) => thread.id === threadId,
        );
        const sessionId = claudeSessionIdByChatRef.current[threadId]
          ?? (storedThread?.filePath ? threadId : null);
        claudeStreamItemIdByChatRef.current[threadId] = streamItemId;
        maybeSetImmediateThreadTitle(workspace.id, threadId, finalText);
        dispatch({
          type: "upsertItem",
          workspaceId: workspace.id,
          threadId,
          item: {
            id: `${threadId}-user-${timestamp}`,
            kind: "message",
            role: "user",
            text: finalText,
          },
        });
        recordThreadActivity(workspace.id, threadId, timestamp);
        dispatch({ type: "setThreadTimestamp", workspaceId: workspace.id, threadId, timestamp });
        markProcessing(threadId, true);
        safeMessageActivity();
        try {
          const response = await sendClaudeCodePrompt(
            threadId,
            workspace.id,
            finalText,
            sessionId,
            model,
            accessMode === "full-access" ? "bypassPermissions" : "default",
          );
          if (response.sessionId) {
            claudeSessionIdByChatRef.current[threadId] = response.sessionId;
          }
          // If text streamed live, the bubble(s) already hold it; passing the
          // full response.text here would duplicate text across the rotated
          // tool-interleaved bubbles. Only fall back to response.text when the
          // stream produced no deltas.
          const hadStreamDelta =
            claudeStreamStateByChatRef.current[threadId]?.hadDelta === true;
          const streamState = claudeStreamStateByChatRef.current[threadId];
          let convertedTextQuestion = false;
          if (hadStreamDelta && streamState) {
            for (const [itemId, text] of streamState.textByItemId) {
              const userInput = buildClaudeCodeTextUserInputItem({ id: itemId, text });
              if (userInput) {
                convertedTextQuestion = true;
                dispatch({
                  type: "upsertItem",
                  workspaceId: workspace.id,
                  threadId,
                  item: userInput,
                });
              }
            }
          }
          if (!hadStreamDelta) {
            const userInput = buildClaudeCodeTextUserInputItem({
              id: streamItemId,
              text: response.text,
            });
            if (userInput) {
              convertedTextQuestion = true;
              dispatch({
                type: "upsertItem",
                workspaceId: workspace.id,
                threadId,
                item: userInput,
              });
            }
          }
          if (!convertedTextQuestion) {
            dispatch({
              type: "completeAgentMessage",
              workspaceId: workspace.id,
              threadId,
              itemId: streamItemId,
              text: hadStreamDelta ? "" : response.text,
              hasCustomName: Boolean(getCustomName(workspace.id, threadId)),
              provider: "claude_code",
            });
          }
          return { status: "sent" };
        } catch (error) {
          pushThreadErrorMessage(
            threadId,
            error instanceof Error ? error.message : String(error),
          );
          return { status: "blocked" };
        } finally {
          delete claudeStreamItemIdByChatRef.current[threadId];
          delete claudeStreamStateByChatRef.current[threadId];
          markProcessing(threadId, false);
          safeMessageActivity();
        }
      }
      const isProcessing = threadStatusById[threadId]?.isProcessing ?? false;
      const activeTurnId = activeTurnIdByThread[threadId] ?? null;
      const {
        resolvedModel,
        resolvedEffort,
        resolvedServiceTier,
        sanitizedCollaborationMode,
        resolvedAccessMode,
        appMentions,
        sendIntent,
        shouldSteer,
        requestMode,
      } = resolveSendMessageOptions({
        options,
        defaults: {
          accessMode,
          model,
          effort,
          serviceTier,
          collaborationMode,
          steerEnabled,
          isProcessing,
          activeTurnId,
        },
      });
      Sentry.metrics.count("prompt_sent", 1, {
        attributes: {
          workspace_id: workspace.id,
          thread_id: threadId,
          has_images: rpcImages.length > 0 ? "true" : "false",
          text_length: String(finalText.length),
          model: resolvedModel ?? "unknown",
          effort: resolvedEffort ?? "unknown",
          service_tier: resolvedServiceTier ?? "default",
          collaboration_mode: sanitizedCollaborationMode ?? "unknown",
          send_intent: sendIntent,
        },
      });
      const timestamp = Date.now();
      const customThreadName = getCustomName(workspace.id, threadId) ?? null;
      recordThreadActivity(workspace.id, threadId, timestamp);
      dispatch({
        type: "setThreadTimestamp",
        workspaceId: workspace.id,
        threadId,
        timestamp,
      });
      markProcessing(threadId, true);
      safeMessageActivity();
      onDebug?.({
        id: `${Date.now()}-${shouldSteer ? "client-turn-steer" : "client-turn-start"}`,
        timestamp: Date.now(),
        source: "client",
        label: shouldSteer ? "turn/steer" : "turn/start",
        payload: {
          workspaceId: workspace.id,
          threadId,
          turnId: activeTurnId,
          text: finalText,
          images: rpcImages,
          model: resolvedModel,
          effort: resolvedEffort,
          serviceTier: resolvedServiceTier,
          collaborationMode: sanitizedCollaborationMode,
          sendIntent,
          threadCustomName: customThreadName,
        },
      });
      try {
        void maybeGenerateInitialThreadTitle(workspace.id, threadId, finalText);
        const shouldPreflightRuntimeCodexArgs =
          shouldPreflightRuntimeCodexArgsForSend?.(workspace.id, threadId) ?? true;
        if (
          !shouldSteer &&
          shouldPreflightRuntimeCodexArgs &&
          ensureWorkspaceRuntimeCodexArgs
        ) {
          await ensureWorkspaceRuntimeCodexArgs(workspace.id, threadId);
        }
        const response: Record<string, unknown> = shouldSteer
          ? (await (appMentions.length > 0
            ? steerTurnService(
              workspace.id,
              threadId,
              activeTurnId ?? "",
              finalText,
              rpcImages,
              appMentions,
            )
            : steerTurnService(
              workspace.id,
              threadId,
              activeTurnId ?? "",
              finalText,
              rpcImages,
            ))) as Record<string, unknown>
          : (await sendUserMessageService(
            workspace.id,
            threadId,
            finalText,
            buildTurnStartPayload({
              model: resolvedModel,
              effort: resolvedEffort,
              serviceTier: resolvedServiceTier,
              collaborationMode: sanitizedCollaborationMode,
              accessMode: resolvedAccessMode,
              images: rpcImages,
              appMentions,
            }),
          )) as Record<string, unknown>;

        const rpcError = extractRpcErrorMessage(response);

        onDebug?.({
          id: `${Date.now()}-${requestMode === "steer" ? "server-turn-steer" : "server-turn-start"}`,
          timestamp: Date.now(),
          source: "server",
          label: requestMode === "steer" ? "turn/steer response" : "turn/start response",
          payload: response,
        });
        if (rpcError) {
          if (requestMode !== "steer") {
            markProcessing(threadId, false);
            setActiveTurnId(threadId, null);
            pushThreadErrorMessage(threadId, String(t("messages.turnFailedToStartWithError", { error: rpcError })));
            safeMessageActivity();
            return { status: "blocked" };
          }
          if (isStaleSteerTurnError(rpcError)) {
            markProcessing(threadId, false);
            setActiveTurnId(threadId, null);
          }
          pushThreadErrorMessage(
            threadId,
            String(t("messages.turnSteerFailed", { error: rpcError })),
          );
          safeMessageActivity();
          return { status: "steer_failed" };
        }
        if (requestMode === "steer") {
          const result = (response?.result ?? response) as Record<string, unknown>;
          const steeredTurnId = asString(result?.turnId ?? result?.turn_id ?? "");
          if (steeredTurnId) {
            setActiveTurnId(threadId, steeredTurnId);
          }
          return { status: "sent" };
        }
        const result = (response?.result ?? response) as Record<string, unknown>;
        const turn = (result?.turn ?? response?.turn ?? null) as
          | Record<string, unknown>
          | null;
        const turnId = asString(turn?.id ?? "");
        if (!turnId) {
          markProcessing(threadId, false);
          setActiveTurnId(threadId, null);
          pushThreadErrorMessage(threadId, String(t("messages.turnFailedToStart")));
          safeMessageActivity();
          return { status: "blocked" };
        }
        setActiveTurnId(threadId, turnId);
        return { status: "sent" };
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        if (requestMode !== "steer") {
          markProcessing(threadId, false);
          setActiveTurnId(threadId, null);
        } else if (isStaleSteerTurnError(errorMessage)) {
          markProcessing(threadId, false);
          setActiveTurnId(threadId, null);
        }
        onDebug?.({
          id: `${Date.now()}-${requestMode === "steer" ? "client-turn-steer-error" : "client-turn-start-error"}`,
          timestamp: Date.now(),
          source: "error",
          label: requestMode === "steer" ? "turn/steer error" : "turn/start error",
          payload: errorMessage,
        });
        pushThreadErrorMessage(
          threadId,
          requestMode === "steer"
            ? String(t("messages.turnSteerFailed", { error: errorMessage }))
            : errorMessage,
        );
        safeMessageActivity();
        return { status: requestMode === "steer" ? "steer_failed" : "blocked" };
      }
    },
    [
      accessMode,
      collaborationMode,
      customPrompts,
      dispatch,
      effort,
      serviceTier,
      ensureWorkspaceRuntimeCodexArgs,
      shouldPreflightRuntimeCodexArgsForSend,
      activeTurnIdByThread,
      getCustomName,
      itemsByThread,
      markProcessing,
      maybeGenerateInitialThreadTitle,
      maybeSetImmediateThreadTitle,
      model,
      onDebug,
      pendingInterruptsRef,
      pushThreadErrorMessage,
      recordThreadActivity,
      renameThread,
      safeMessageActivity,
      setActiveTurnId,
      steerEnabled,
      threadsByWorkspace,
      threadStatusById,
      t,
    ],
  );

  const sendUserMessage = useCallback(
    async (
      text: string,
      images: string[] = [],
      appMentions: AppMention[] = [],
      options?: { sendIntent?: ComposerSendIntent },
    ): Promise<SendMessageResult> => {
      if (!activeWorkspace) {
        return { status: "blocked" };
      }
      const messageText = text.trim();
      if (!messageText && images.length === 0) {
        return { status: "blocked" };
      }
      const promptExpansion = expandCustomPromptText(messageText, customPrompts);
      if (promptExpansion && "error" in promptExpansion) {
        if (activeThreadId) {
          pushThreadErrorMessage(activeThreadId, promptExpansion.error);
          safeMessageActivity();
        } else {
          onDebug?.({
            id: `${Date.now()}-client-prompt-expand-error`,
            timestamp: Date.now(),
            source: "error",
            label: "prompt/expand error",
            payload: promptExpansion.error,
          });
        }
        return { status: "blocked" };
      }
      const finalText = promptExpansion?.expanded ?? messageText;
      const threadId = await ensureThreadForActiveWorkspace();
      if (!threadId) {
        return { status: "blocked" };
      }
      return sendMessageToThread(activeWorkspace, threadId, finalText, images, {
        skipPromptExpansion: true,
        appMentions,
        sendIntent: options?.sendIntent,
      });
    },
    [
      activeThreadId,
      activeWorkspace,
      customPrompts,
      ensureThreadForActiveWorkspace,
      onDebug,
      pushThreadErrorMessage,
      safeMessageActivity,
      sendMessageToThread,
    ],
  );

  const sendUserMessageToThread = useCallback(
    async (
      workspace: WorkspaceInfo,
      threadId: string,
      text: string,
      images: string[] = [],
      options?: SendMessageOptions,
    ): Promise<SendMessageResult> => {
      return sendMessageToThread(workspace, threadId, text, images, options);
    },
    [sendMessageToThread],
  );

  const interruptTurn = useCallback(async () => {
    if (!activeWorkspace || !activeThreadId) {
      return;
    }
    if (activeWorkspace.source === "claude_code") {
      await stopClaudeCodePrompt(activeThreadId).catch(() => false);
      markProcessing(activeThreadId, false);
      delete claudeStreamItemIdByChatRef.current[activeThreadId];
      delete claudeStreamStateByChatRef.current[activeThreadId];
      return;
    }
    const activeTurnId = activeTurnIdByThread[activeThreadId] ?? null;
    const turnId = activeTurnId ?? "pending";
    setInterruptedTurnId(activeThreadId, activeTurnId);
    markProcessing(activeThreadId, false);
    setActiveTurnId(activeThreadId, null);
    dispatch({
      type: "addAssistantMessage",
      threadId: activeThreadId,
      text: String(t("messages.sessionStopped")),
    });
    if (!activeTurnId) {
      pendingInterruptsRef.current.add(activeThreadId);
    }
    onDebug?.({
      id: `${Date.now()}-client-turn-interrupt`,
      timestamp: Date.now(),
      source: "client",
      label: "turn/interrupt",
      payload: {
        workspaceId: activeWorkspace.id,
        threadId: activeThreadId,
        turnId,
        queued: !activeTurnId,
      },
    });
    try {
      const response = await interruptTurnService(
        activeWorkspace.id,
        activeThreadId,
        turnId,
      );
      onDebug?.({
        id: `${Date.now()}-server-turn-interrupt`,
        timestamp: Date.now(),
        source: "server",
        label: "turn/interrupt response",
        payload: response,
      });
    } catch (error) {
      onDebug?.({
        id: `${Date.now()}-client-turn-interrupt-error`,
        timestamp: Date.now(),
        source: "error",
        label: "turn/interrupt error",
        payload: error instanceof Error ? error.message : String(error),
      });
    }
  }, [
    activeThreadId,
    activeTurnIdByThread,
    activeWorkspace,
    dispatch,
    markProcessing,
    onDebug,
    pendingInterruptsRef,
    setActiveTurnId,
    setInterruptedTurnId,
    t,
  ]);

  const startReviewTarget = useCallback(
    async (target: ReviewTarget, workspaceIdOverride?: string): Promise<boolean> => {
      const workspaceId = workspaceIdOverride ?? activeWorkspace?.id ?? null;
      if (!workspaceId) {
        return false;
      }
      const threadId = workspaceIdOverride
        ? await ensureThreadForWorkspace(workspaceId)
        : await ensureThreadForActiveWorkspace();
      if (!threadId) {
        return false;
      }

      const lockParentThread = reviewDeliveryMode !== "detached";
      if (lockParentThread) {
        markProcessing(threadId, true);
        markReviewing(threadId, true);
        safeMessageActivity();
      }
      onDebug?.({
        id: `${Date.now()}-client-review-start`,
        timestamp: Date.now(),
        source: "client",
        label: "review/start",
        payload: {
          workspaceId,
          threadId,
          target,
        },
      });
      try {
        const response = await startReviewService(
          workspaceId,
          threadId,
          target,
          reviewDeliveryMode,
        );
        onDebug?.({
          id: `${Date.now()}-server-review-start`,
          timestamp: Date.now(),
          source: "server",
          label: "review/start response",
          payload: response,
        });
        const rpcError = extractRpcErrorMessage(response);
        if (rpcError) {
          if (lockParentThread) {
            markProcessing(threadId, false);
            markReviewing(threadId, false);
            setActiveTurnId(threadId, null);
          }
          pushThreadErrorMessage(threadId, String(t("messages.reviewFailedToStart", { error: rpcError })));
          safeMessageActivity();
          return false;
        }
        const reviewThreadId = extractReviewThreadId(response);
        if (reviewThreadId && reviewThreadId !== threadId) {
          updateThreadParent(threadId, [reviewThreadId]);
          if (reviewDeliveryMode === "detached") {
            registerDetachedReviewChild?.(workspaceId, threadId, reviewThreadId);
            const reviewTitle = buildReviewThreadTitle(target, t);
            if (reviewTitle && !getCustomName(workspaceId, reviewThreadId)) {
              renameThread?.(workspaceId, reviewThreadId, reviewTitle);
            }
          }
        }
        return true;
      } catch (error) {
        if (lockParentThread) {
          markProcessing(threadId, false);
          markReviewing(threadId, false);
        }
        onDebug?.({
          id: `${Date.now()}-client-review-start-error`,
          timestamp: Date.now(),
          source: "error",
          label: "review/start error",
          payload: error instanceof Error ? error.message : String(error),
        });
        pushThreadErrorMessage(
          threadId,
          error instanceof Error ? error.message : String(error),
        );
        safeMessageActivity();
        return false;
      }
    },
    [
      activeWorkspace,
      ensureThreadForActiveWorkspace,
      ensureThreadForWorkspace,
      getCustomName,
      markProcessing,
      markReviewing,
      onDebug,
      pushThreadErrorMessage,
      safeMessageActivity,
      setActiveTurnId,
      reviewDeliveryMode,
      registerDetachedReviewChild,
      renameThread,
      updateThreadParent,
      t,
    ],
  );

  const {
    reviewPrompt,
    openReviewPrompt,
    closeReviewPrompt,
    showPresetStep,
    choosePreset,
    highlightedPresetIndex,
    setHighlightedPresetIndex,
    highlightedBranchIndex,
    setHighlightedBranchIndex,
    highlightedCommitIndex,
    setHighlightedCommitIndex,
    handleReviewPromptKeyDown,
    confirmBranch,
    selectBranch,
    selectBranchAtIndex,
    selectCommit,
    selectCommitAtIndex,
    confirmCommit,
    updateCustomInstructions,
    confirmCustom,
  } = useReviewPrompt({
    activeWorkspace,
    activeThreadId,
    onDebug,
    startReviewTarget,
  });

  const startReview = useCallback(
    async (text: string) => {
      if (!activeWorkspace || !text.trim()) {
        return;
      }
      const trimmed = text.trim();
      const rest = trimmed.replace(/^\/review\b/i, "").trim();
      if (!rest) {
        openReviewPrompt();
        return;
      }

      const target = parseReviewTarget(trimmed);
      await startReviewTarget(target);
    },
    [
      activeWorkspace,
      openReviewPrompt,
      startReviewTarget,
    ],
  );

  const startUncommittedReview = useCallback(
    async (workspaceId?: string | null) => {
      const workspaceOverride = workspaceId ?? undefined;
      await startReviewTarget({ type: "uncommittedChanges" }, workspaceOverride);
    },
    [startReviewTarget],
  );

  const startStatus = useCallback(
    async (_text: string) => {
      if (!activeWorkspace) {
        return;
      }
      const threadId = await ensureThreadForActiveWorkspace();
      if (!threadId) {
        return;
      }

      const lines = buildStatusLines({
        model,
        serviceTier,
        effort,
        accessMode,
        collaborationMode,
        rateLimits: rateLimitsByWorkspace[activeWorkspace.id] ?? null,
        t,
      });
      const timestamp = Date.now();
      recordThreadActivity(activeWorkspace.id, threadId, timestamp);
      dispatch({
        type: "addAssistantMessage",
        threadId,
        text: lines.join("\n"),
      });
      safeMessageActivity();
    },
    [
      accessMode,
      activeWorkspace,
      collaborationMode,
      dispatch,
      effort,
      ensureThreadForActiveWorkspace,
      model,
      serviceTier,
      rateLimitsByWorkspace,
      recordThreadActivity,
      safeMessageActivity,
      t,
    ],
  );

  const startFast = useCallback(
    async (text: string) => {
      if (!activeWorkspace) {
        return;
      }
      const threadId = await ensureThreadForActiveWorkspace();
      if (!threadId) {
        return;
      }

      const action = parseFastCommand(text);
      const isEnabled = serviceTier === "fast";
      let nextTier = serviceTier ?? null;
      let message = "";

      if (action === "invalid") {
        message = String(t("messages.fastUsage"));
      } else if (action === "status") {
        message = isEnabled ? String(t("messages.fastModeOn")) : String(t("messages.fastModeOff"));
      } else {
        nextTier =
          action === "on"
            ? "fast"
            : action === "off"
              ? null
              : isEnabled
                ? null
                : "fast";
        onSelectServiceTier?.(nextTier);
        message = nextTier === "fast" ? String(t("messages.fastModeEnabled")) : String(t("messages.fastModeDisabled"));
      }

      const timestamp = Date.now();
      recordThreadActivity(activeWorkspace.id, threadId, timestamp);
      dispatch({
        type: "addAssistantMessage",
        threadId,
        text: message,
      });
      safeMessageActivity();
    },
    [
      activeWorkspace,
      dispatch,
      ensureThreadForActiveWorkspace,
      onSelectServiceTier,
      recordThreadActivity,
      safeMessageActivity,
      serviceTier,
      t,
    ],
  );

  const startMcp = useCallback(
    async (_text: string) => {
      if (!activeWorkspace) {
        return;
      }
      const threadId = await ensureThreadForActiveWorkspace();
      if (!threadId) {
        return;
      }

      try {
        const response = (await listMcpServerStatusService(
          activeWorkspace.id,
          null,
          null,
        )) as Record<string, unknown> | null;
        const result = (response?.result ?? response) as
          | Record<string, unknown>
          | null;
        const data = Array.isArray(result?.data)
          ? (result?.data as Array<Record<string, unknown>>)
          : [];
        const lines = buildMcpStatusLines(data, t);

        const timestamp = Date.now();
        recordThreadActivity(activeWorkspace.id, threadId, timestamp);
        dispatch({
          type: "addAssistantMessage",
          threadId,
          text: lines.join("\n"),
        });
      } catch (error) {
        const message =
          error instanceof Error ? error.message : String(t("messages.failedToLoadMcpStatus"));
        dispatch({
          type: "addAssistantMessage",
          threadId,
          text: String(t("messages.mcpToolsError", { error: message })),
        });
      } finally {
        safeMessageActivity();
      }
    },
    [
      activeWorkspace,
      dispatch,
      ensureThreadForActiveWorkspace,
      recordThreadActivity,
      safeMessageActivity,
      t,
    ],
  );

  const startApps = useCallback(
    async (_text: string) => {
      if (!activeWorkspace) {
        return;
      }
      const threadId = await ensureThreadForActiveWorkspace();
      if (!threadId) {
        return;
      }

      try {
        const response = (await getAppsListService(
          activeWorkspace.id,
          null,
          100,
          threadId,
        )) as Record<string, unknown> | null;
        const result = (response?.result ?? response) as
          | Record<string, unknown>
          | null;
        const data = Array.isArray(result?.data)
          ? (result?.data as Array<Record<string, unknown>>)
          : [];
        const lines = buildAppsLines(data, t);

        const timestamp = Date.now();
        recordThreadActivity(activeWorkspace.id, threadId, timestamp);
        dispatch({
          type: "addAssistantMessage",
          threadId,
          text: lines.join("\n"),
        });
      } catch (error) {
        const message =
          error instanceof Error ? error.message : String(t("messages.failedToLoadApps"));
        dispatch({
          type: "addAssistantMessage",
          threadId,
          text: String(t("messages.appsError", { error: message })),
        });
      } finally {
        safeMessageActivity();
      }
    },
    [
      activeWorkspace,
      dispatch,
      ensureThreadForActiveWorkspace,
      recordThreadActivity,
      safeMessageActivity,
      t,
    ],
  );

  const startFork = useCallback(
    async (text: string) => {
      if (!activeWorkspace || !activeThreadId) {
        return;
      }
      const trimmed = text.trim();
      const rest = trimmed.replace(/^\/fork\b/i, "").trim();
      const threadId = await forkThreadForWorkspace(activeWorkspace.id, activeThreadId);
      if (!threadId) {
        return;
      }
      updateThreadParent(activeThreadId, [threadId]);
      if (rest) {
        await sendMessageToThread(activeWorkspace, threadId, rest, []);
      }
    },
    [
      activeThreadId,
      activeWorkspace,
      forkThreadForWorkspace,
      sendMessageToThread,
      updateThreadParent,
    ],
  );

  const startResume = useCallback(
    async (_text: string) => {
      if (!activeWorkspace) {
        return;
      }
      if (activeThreadId && threadStatusById[activeThreadId]?.isProcessing) {
        return;
      }
      const threadId = activeThreadId ?? (await ensureThreadForActiveWorkspace());
      if (!threadId) {
        return;
      }
      await refreshThread(activeWorkspace.id, threadId);
      safeMessageActivity();
    },
    [
      activeThreadId,
      activeWorkspace,
      ensureThreadForActiveWorkspace,
      refreshThread,
      safeMessageActivity,
      threadStatusById,
    ],
  );

  const startCompact = useCallback(
    async (_text: string) => {
      if (!activeWorkspace) {
        return;
      }
      const threadId = activeThreadId ?? (await ensureThreadForActiveWorkspace());
      if (!threadId) {
        return;
      }
      try {
        await compactThreadService(activeWorkspace.id, threadId);
      } catch (error) {
        pushThreadErrorMessage(
          threadId,
          error instanceof Error
            ? error.message
            : String(t("messages.failedToStartContextCompaction")),
        );
      } finally {
        safeMessageActivity();
      }
    },
    [
      activeThreadId,
      activeWorkspace,
      ensureThreadForActiveWorkspace,
      pushThreadErrorMessage,
      safeMessageActivity,
      t,
    ],
  );

  return {
    interruptTurn,
    sendUserMessage,
    sendUserMessageToThread,
    startFork,
    startReview,
    startUncommittedReview,
    startResume,
    startCompact,
    startApps,
    startMcp,
    startFast,
    startStatus,
    reviewPrompt,
    openReviewPrompt,
    closeReviewPrompt,
    showPresetStep,
    choosePreset,
    highlightedPresetIndex,
    setHighlightedPresetIndex,
    highlightedBranchIndex,
    setHighlightedBranchIndex,
    highlightedCommitIndex,
    setHighlightedCommitIndex,
    handleReviewPromptKeyDown,
    confirmBranch,
    selectBranch,
    selectBranchAtIndex,
    selectCommit,
    selectCommitAtIndex,
    confirmCommit,
    updateCustomInstructions,
    confirmCustom,
  };
}
